### ISSUE TITLE
looses theme on iOS if orientation changes

### ISSUE THREAD

**Issue by ekke** [jpnurmi/statusbar#4] opened 2018-10-26 08:24 UTC
Hi JP,
thx for StatusBar - works great on Android and iOS.
found a small problel on iOS
have set StatusBar theme to StatusBar.Dark --> text and icons in StatusBar are white
if orientation changes, then StatusBar looses the theme and text and icons are black
this is my workaround:
if orientation changes on iOS, toggle the Theme, then set it back via Timer
`if(Qt.platform.os === "ios") {
            toggleStatusBarTheme()
        }
function toggleStatusBarTheme() {
        if(theStatusBar.theme === StatusBar.Light) {
            theStatusBar.theme = StatusBar.Dark
        } else {
            theStatusBar.theme = StatusBar.Light
        }
        statusBarTimer.start()
    }
    Timer {
        id: statusBarTimer
        interval: 200
        repeat: false
        onTriggered: {
            theStatusBar.theme = StatusBar.Dark
        }
    }
`

**Comment by jpnurmi** [comment] 2018-10-26 20:43
Hi ekke, I don't have a development environment for iOS these days, but you could try adding screen orientation change handling to StatusBarPrivate::setTheme_sys() in src/statusbar_ios.mm. Something similar to the already existing application state change handling, which is there as a workaround for fighting against Qt's internal statusbar updates, if I remember correctly. I could imagine the reason for losing the theme on orientation changes is similar to losing it on application state changes. I'd try connecting to QGuiApp::primaryScreen()'s orientationChanged() signal and call updatePreferredStatusBarStyle(), similarly.

**Comment by jpnurmi** [comment] 2018-10-26 20:53
The problem is basically that updateProperties() in Qt's [qiosviewcontroller.mm](https://code.woboq.org/qt5/qtbase/src/plugins/platforms/ios/qiosviewcontroller.mm.html#420) overrides preferredStatusBarStyle.

**Comment by ekke** [comment] 2018-10-27 17:45
Hi JP,
thx
will try out to connect to orientationChanged()signal

**Comment by ekke** [comment] 2018-10-30 15:10
Hi JP, tried to connect to orientationChanged() SIGNAL, but couldn't figure out the correct connect syntax for 
`QGuiApplication::primaryScreen::orientationChanged`

**Comment by jpnurmi** [comment] 2018-10-30 15:21
Would something like this work?

    QScreen *screen = qApp->primaryScreen();
    screen->setOrientationUpdateMask(Qt::PortraitOrientation | Qt::LandscapeOrientation | Qt::InvertedPortraitOrientation | Qt::InvertedLandscapeOrientation);
    QObject::connect(screen, &QScreen::orientationChanged, qApp, [](Qt::ScreenOrientation) {
        updatePreferredStatusBarStyle();
    }, Qt::UniqueConnection);

**Comment by ekke** [comment] 2018-10-30 15:41
aaah - the trick was
`QScreen *screen = qApp->primaryScreen();`
have thought I could do it in one step from
`QGuiApplication::primaryScreen::orientationChanged`

it gets the signal and updatePreferredStatusBarStyle was called, but the theme wasn't set.
So it seems I should stay with my QML Timer solution: at orientation changed setting the opposite theme, start Timer and reset default theme

**Comment by ekke** [comment] 2018-10-30 16:49
now found a solution without additional code in QML:
`
void StatusBarPrivate::setTheme_sys(StatusBar::Theme)
{
    updatePreferredStatusBarStyle();
    // ...
    QScreen *screen = qApp->primaryScreen();
    screen->setOrientationUpdateMask(Qt::PortraitOrientation | Qt::LandscapeOrientation | Qt::InvertedPortraitOrientation | Qt::InvertedLandscapeOrientation);
    QObject::connect(screen, &QScreen::orientationChanged, qApp, [](Qt::ScreenOrientation) {
        togglePreferredStatusBarStyle();
    }, Qt::UniqueConnection);
}
`

then toggle them to oppsite theme and start timer to set default
`
void togglePreferredStatusBarStyle()
{
    UIStatusBarStyle style = statusBarStyle(StatusBar::Light);
    if(StatusBarPrivate::theme == StatusBar::Light) {
        style = statusBarStyle(StatusBar::Dark);
    }
    UIWindow *keyWindow = [[UIApplication sharedApplication] keyWindow];
    if (keyWindow)
        setPreferredStatusBarStyle(keyWindow, style);

    QTimer* timer = new QTimer();
    timer->setInterval(200);
    timer->setSingleShot(true);
    QObject::connect(timer, &QTimer::timeout, timer, []() {
        UIStatusBarStyle style = statusBarStyle(StatusBarPrivate::theme);
        UIWindow *keyWindow = [[UIApplication sharedApplication] keyWindow];
        if (keyWindow)
            setPreferredStatusBarStyle(keyWindow, style);
    }, Qt::UniqueConnection);
    timer->start();
}
`

hopefully it's correct to use the QTimer in this way
(couldn't get the code highlighting working as expected ;-)

**Comment by jpnurmi** [comment] 2018-11-01 08:12
Fixed by #5.

**Closed as completed by jpnurmi** 2018-11-01 08:12 UTC
